# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='hairiness',
            field=models.IntegerField(default=False, help_text=b'100 its max of hairiness'),
        ),
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='cat',
            name='species',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='paw',
            field=models.IntegerField(default=4, help_text=b'number of paw(usually its 4)'),
        ),
    ]
