# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0004_auto_20170830_1640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cat',
            table='cat',
        ),
    ]
