# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0005_auto_20170830_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='hairiness',
            field=models.IntegerField(default=False, help_text=b'100 its max'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='paw',
            field=models.IntegerField(default=4),
        ),
    ]
