# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0006_auto_20170831_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='hairiness',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(default=b'Cat', max_length=30),
        ),
    ]
