# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0008_auto_20170920_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
