# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 11:48
from __future__ import unicode_literals

import catbuilder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0010_auto_20170921_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catbuilder.models.upload_location),
        ),
    ]
