# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0011_auto_20170921_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='text',
            field=models.CharField(blank=True, default=False, max_length=500),
        ),
    ]
