# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbuilder', '0013_auto_20170924_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='text',
            field=models.CharField(blank=True, default=b'Write your cat history here', max_length=2000),
        ),
    ]
